text = 'HGMEEKGDEOMFHNJEIANEOELKNLMPCPKPIDNHOEGKIHDAAAJFNDAIJGDOBCKNADADJHNIAOHANMOHFBBIFMAAAAOHCFAMEDFDPEMBEMNDLEEPCEDOOIANACJOODOCKHKLNGCAHAMBAONMECGMBNOAIPBECLAAJPEAHCMHEDMCNBCFGDNCILFHGOKKPKCOIMPOAMOLIMFACAAOIBBLNLDOPGAFBPEKIDPBHEAHABOHHPCOIFFBAPOFNOMNBDHOIAOEICDAPJJKOJANADNIPMKNIMJDBIFKKNMEEPKAINLMDOAEOBFNAOACJANNPLKFACJMIOAEJMOOPBMMEIDFGGMHCEBFCICAAJGLGDOEINLFCNMKIKJBCHFGNDCMCGFDPMHFAAODOJGAGGDHFMGBKCOIOJNKJNKDPDEBAGKHIKGAMHINOKCMPJMIEFHDEJKEOKJMHAOIILBCBOKAJFBOJFNJABHABFAHFOAMAHILEBPAFDMKICKMAMNDABIAEIDAJANNKFOIOEEKFMODPDJGAOOGOCEAANAAJCDEEIJPAJHGJEHJAIHMAOJOADKANKNJABMCAHCCEFDAKNMDHOIBGEMECLFFCNMOICNAADFIMJGAKJKDHDKFHDKIIBECPIKKKMLNGPOEILLFBFMAJFMKJCFMNBCAIIFDPOEEHPAOAMFCHKOCKNHBNCMEEKBBFNMKKKHOAAEIJOHAPBKIECHCHDKOICLCICOKKFBHFNKAIJHHFINONIKOIPEKOOOOKGCHFJMDACECBNCAOJMMCABICHOHIMDMEHHAAFOMNDDAPEKFCHFKIALAANHJFIMNCKAKIBAHHDMAEGADCBAOIEIGOCMAECINNMACHCNNDBAIACGDFEKOIFOBNPKIIOOOFMKCHEAFFBAAAONHCOAHFMAOCGNEAHEKHLMNOBKFFKFEGMEHIOMMCHJPIBDEHNIKMPDAACIJKLFAMPACEAAAJDJCPAFIAEBDJPKOOGPHCJAIANMMEPKHFGMBIBCGHONKENFHHFNFPJHEFKADPHMOIFLPBDOAIILENDAAJMMHIOAHACNKLBHOIIAOJCCMHBNAAJFKICFIHHAOADPHNCOCKMAPGENIOEJFJLKAJDAPADNKGGPAKAJHFHKCACACJHHNEOKAABNPOCDAPILOAPANAGBBFKAAJDFHDMNEBPEFAFEKBEBAKPKCHBLPIFDAPBHKNOAFMIOINGKDIGGOHADHHCPNIKFFGNLKGHHKINECJEMIEBGACGKDPBHDEJMHCLEMBLDAAAKMIBAKAIIKLNKFNMIOICCJHDFKBEAKILAJEEFPGBIMIJDOIEBFMJAKJNOFJECFNEEJODCKHEEOCLKAACHFEHBENNDMHIIMEOFMCGAAADMMLENEJHDFHFFIMKADFAODHCAAIMDEHKOKFODAAKKPHLFIMKADAHOAJFAJANOAIEHFGMAAAJPHGHKIIIHFFDKNOBABKNFAMGMCGGACHDPFPEHBFDODFHEEBEHMCDONIEFMNGFDPCBKEPHHHGEMMDCAADIJEFFAMBBINMAHFBNPEKAIADGOHBOHMMDFINDJPMBOBHAMCHEPICNEOIDODLIMCFECAPOOICJANEEAAHFDGAMICIFFDOKMENJMMIAAAIOHCCAIENNDHBNEOJDCGLMOOPNDEPDJPLCMBFAHHKHDEFFAMAAMMJAAJPHIEINIAFEIALKCHCNMAFFFMHJAENHAJIOFPPKNIMNDFNFONNCGEFDHDHCMMKCAAMPCJPNIAPNAHKKDHEDOIBHPHJMKANDLDIHEOCMICILNMJKFNFHPDBAHAENDCHCIEKHDIDACJGKOJKPNAFPJDPAFADDCGMOFMIGEAEODFGFAJNDAGHMEEDAIACJOAIONGKBFIEDJPNJOKIAMCNLKIPNEOGJOPBIMCGDAOGCKHOBOIBKAANMFAEBCNLNAFAMMEGHNGEMICGOFDGKKIEJBAPDIPEOAAIOEBKDBGNAHAMKFODCFAJFIDKCCKHKLDNKMEJAFMJFHGGDFNNCMEBGAABCHKBCAPDHMEGOEIIDCPNMKMOMKIPDOKHKEIBJKEKDAABDLABIDEPCANHDMEABPKMOIODHKJIODPHMMEKKAILKIKKAAJJIJEKJGAICGFAHAGCJAOJAHAMANHGDJAJJEACOIINKACOOAAGINPAMAENDDAJADHOGMCMOGOGHMCMFDDDEFADJCPJPAGIMOOPBENCFAGOBFKNAMEINNAKCJHLFNOAAFGAIFEHMJEKDIFFEEOCCDIJCNKJAKEAOAABJNANHCFBIADCMKICHDKFKEIKKKGKDKIDPJIKABJALOHHEMEJPCHCAHAJAHIDCEJBHHIEFFGPJOPKHKIDAJANFJGKANLEAKIJKMFIKMIDMHNMFNOPMFHAAFAMACFJHCKNIPJLHAFKCEBBAKINIHIPCFHMAKMOHHHPCBIMDCPLIKBGKKIGNAKJFAMIACECAAJFDMHDAIAHJDBIOOIMOOMEAKJHNFMICAJNCMACFDAIANBGDAAODANCNNAMOBEJOCHGGPICAEJHNONDIMECNMKNAPAKIKHIDEJKBGNGAAJDBOIENOIPMBEEMAEEBIGOABNOIJIPADAECKPBDOIANGFHMMEJDHEBFAJAFIHBAIAEMHOBKCKBBHCIOIIAHPJOOFAJMAAFNKGFCANDJIEHBJANACJNMNKIKAAOGOOBDAPNOOKBANACICKJOPFCABKBHCDHGMGGDADHGNEKAAAPJHAMNJACBAEOAAJPDMACDJHIAAFHAMEGNDKAOIIAAKCNKNAKJPEKMAEAEMMPADPDEBPCONIHKDPAFMCFHAABKKIMGAEMKAJKPHABDAPKINCDAFMHDIHMNEOMPCCEMOOCLCEMDJPKFMEMAHHJJBDFAPAAODDFDNACGOJOHAFDOAJLNNACDCHNAIALNHBCKEBKOICHKAIDPMFDNDPBGIKPKIINEKFJKAAFBEJFKMIGIAOCFCHGNKHFAHAGNHBBCEJAPGINCNKKKKMNOKIBECOBHAFIOEPMNOIFOIHMAIAKOHCGKEBHADEKDFPINMOOHAAEIOOLDAHDKOFHAKIAKJHCMEECNCHPMKKFMPACOEOJJAPDODDHNDPCMMCONDANFOIOJKIFAAAJCOCCAEJDDDICMKCLAKJPKKICHBJIAIJEGAAAKMEKBNEDMAEOKMEOAAAFNOAGKCCHLNJAMOOMHAIMNAOEOOFBAFGKMFHCMEEKKCDGMHHHFDCNAIABFMIBKONIJAGMMCEOOFHCMHFAJFHGOIIIPDCIONOLCLPCHAHMCDIKNAAKEHANOHNEHNCOCPCAIMHONIAGNDGFODHNLNEDAGAAJOPCFNGDJMANCBHKANAAEKIJEJIPHPHBNKDEDAAGFBAEMACNNNPPAKIKHJINKHKBNKKGCKIGLFMLAAJOIFHMAKIAFGOKDKPPMOPIKDDMDNIFAEJBGKBJIOIMPHAAHGFPEAIHAAABOBAMHOPLFAFHNGEKMHJEAAAEMAEFNDHOGNNJKIIOLOEGOCKBDICGNNALIMCFFDPHFPAPHDFLDAEKCAAPGDDHGPEKFCBFHPOFMMHGNAOBLDHOAAAHDNAGFHGELAMJHKIDCHEMCNHOIMKBOMEEGCDCMIEELDAEKAJCGPHENAODFCOPNAAHKBDHAPAGCDKGDEBIIHJOHIFDOAKLKNAHEDHGAIAOMHCOKIEFNBCIKMIAJMAAFDPPBLAMOCINHANIMAAPAFGBMICAJFKKKKIALOAFDAPLGNJMAEBDLPAFFNAFGABCOOINHLKDODOHKCDDLHFPCMEHCKHHJMNACFGMILIHDJPPJOJHAAAEDMAFICEFLAOOMOICNOIEDOPJJKDFEHHHHCKKFAMNECDPAAJAHDANCJHNNNFJAFGFKEEAMAEBLIMDAEOHLPICAHAHAKIIHOIDBFJDCMHKFAPKFKINEOHJAOAKHHBJOCKJCEGBNIOPMFKIKAJGKKAHNHGNGAJPFHFGHGGIAAAPEFMPNNAGJMIANNOCAKIEOAJFDDGHMOCGJFEBOKINFNMMAKJEHFEACHHPGLAJAHJOKNIJHAAIECFNNPAKOHFGDCHNCCIPABJEJONJEMEBBMINAHAMBOKEDCKEKAIIDCPEGOIMMMEODNHOAHAAKHMECFNDCDIFFFGBCOADHKIFJAAMFJGJBNPBAKIPFNFAKMICHHIDFNOPGMHPAFADOCPJHMEMMHABNGGBGADKAFMIPNAEBLKENADOAJADFEPAMECDLDDGMKIHJNPFOEOBGJOHDONIIMACMHENAAAPHOIPNEIPDCPOEKNKMKICIHIHAKALCKGJKFMAMBIFCJHLIKHBAKIFGECBAIADCMFPKFMCBBICFBGPMKFCEMCPGBAKOIICGAMOODPLCCIHANAKBKCFOFAFENEDKDIIAINLLAJFMAOEHKFLOOIHCONFGJIMDJPPPOHPAAADLGAOIGEBEAAKFOIGLDJPNOALAAPPECHPHMAFIIEACAJEOMEFHMGBKNIBNFJLOAAAOHNLDJPJIFKGAMEDKCAICIKPBAFLKFMGIKHCKJIDECPMAHHBOFAHCHKFPAFAHFMNHCOBAGJIKNLMFOOCCGJJHAFALEPIAKIPNLOJDKPJLOPIKDDFMLAJAAJEENJHAOIMLMAKCJKEKAMIAOIGLCHJAHAALHJGCMEJLNMBHOFKCFIAEMEBEPAKDAPAKNCOANAAFCGMGAELPAECAPOHNLGKDAHMGNEOANOPGOIHNKADJONJKFHLOCEMDEPLJMIOMKIKCOKMFICNIJJBKAACMGHMFIGKBCAOKAJCGBJAFMNNOAAMFDPCFJFGAAAEPHEJAIECFAPAKIIKODABKDDBLMAAODODGACCLHFPDLGPIIHILFKCKAANCKIBHCHCIKEEKAAKMCAFOGIDGABPFFGAPDAMAAANPLOGLKIABEAAPNONDAOIBJAFOBCBAAABCMPENMEFJAEAKJIJBMPFEDHINPGGKICEMFMOKAAJBJAHOOIHFADBNAAFHBGHAHJEBFNCCKIOIPNHDJPKKFEOAKILBBAHECBPFAHICNAGHGAPNAALNFFBNCHAAGGDAIABEFLEKEJBAMOBFINKMNCIKDPKOLOHDCPAGOLIKAAFIFHMMAEEFMJBAEOOAONCKDINMOEODHHGMFIFFFGBHKDLHKIMGAJFMJEDOANOADPLBPIMDAHCJOFFAFMFMHPNFIMJMDPMOKKBMIMAFPGFAFJNDAAHHOAPHBFKLNEKEKIKPBHHNHADDCAKDAACFNCFIOELMMJLNMEMOHAOEHBAFAHFHNABKHIEDCPKOKODMKIJECIMAKALFKEHKNAADMIECJHKOKOLAKIOOKABEHJKAACCHFMLAKKAKIIGLCPIKCHDMMFCOOIHDHNIEONMMBADEHBMCAEGHNABODHBAOAHBCHBOKIAKGNDMOECABFHOKKPENIHBKMPFKFACAAEOCECKFCBKMBDHNAAHCAJHMMJDADHBAABPCHIMJEHECBEANOFABIEHCFKPOALPMENHGMIAAADDHJMAMEIDEFMKEIEBHAGMFHJPDCNEGBJFMNPFBPIMPMJAAALOHPDAKIAPDHKKAIEKDILNPFCDJFDOAOGDHFHAEOFJPLHAOAKKAPNEHMFEGKCOONNEKBHOMEAIDMKAAAOCHHPABNOJGKEMOELDCBIOBPJJBMDAAAHKHHDAHFFLDKNKJIOOCBNANHBGOAEEIJEIAHJOEBJGIKFKIIFLKKMKAAAEJJPKIIHMAALOCHMPMPCMNEJKDIHFFGHDJBNNAALBEGMAAJFMCPBKIIKODDLKHHNGFJCNAAHHEKLAMCCIHPENPOGPDAJJHFINEFBNOACKHDBEKCMHAACELBIMAIOANAECFEFDHHGHMMPCKICIGCHAOJPFMDBNNAAFOACIIEPDAFKOOIANHEHBAPCCMGEFAAIPKIHCGHADONMFMEBAHIBNEOFHOMPIPCNHHOIOHOBCNHDCAAOHLPGHEHMGDMCMMEJLIMDAEJOPFMOMAJJHJAICEHLDNCFIAAHKDMAAAJAFFNDAKINAEHGAHAHGHCACOIACAIACNKNBKEGOKIFGFOEHAFOGEFMNOICEIHPAIAPJHNKKEBHHFINDJPBOOHLAAAIFCAOOFIOEAFMCOIIMCEPNNAKLIBCOAJCKKPFDPHBLJLCDMEBDIIAAAAFHODEAFNMLIPCNEADKDJDMONLMEHJAIAOAHBMKMEJGHEHCOHECMFJNAAIECAFDHHPAAHIFNAALBCMFEGBDPOLMMEOOJKFAKADCOCHKEJCNAACNIAFOAIJOCHCGFNDOEKGKOIEMAANMGBGNBGMPMEPMCHKIEBOMBBGBMMIMMBCFG'

UNKNOWN_SYMBOL = '_'

blocks = []

start_val = 32
for i in range(len(text)):
    if start_val == 32:
        blocks.append(text[i:i+32])
        start_val = 0
    start_val += 1

sdvig = {
    0 : (12, 11),
    1 : (4, 2),
    2 : (0, 7),
    3 : (3, 10),
    4 : (28, 27),
    5 : (20, 18),
    6 : (16, 23),
    7 : (19, 26),
}

alphabet = {
    'FO' : '9',
    'AA' : ' ',
    'BM' : '*',
    'IK' : 'о',
    'AN' : 'а',
    'NO' : 'д',
    'JA' : 'н',
    'GF' : 'т',
    'ON' : 'к',
    'CM' : 'с',
    'EM' : 'е',
    'NE' : 'Ъ',
    'OO' : 'у',
    'HH' : 'п',
    'MF' : 'ы',
    'KC' : 'х',
    'HD' : 'м',
    'FH' : 'в',
    'IO' : 'и',
    'HC' : 'р',
    'CP' : 'ц',
    'PD' : 'л',
    'CC' : 'ф',
    'HI' : 'э',
    'BE' : 'я',
    'AF' : 'з',
    'KC' : 'х',
    'OE' : 'ш',
    'ED' : 'щ',
    'EI' : 'й',
    'NF' : 'ь',
    'CK' : 'ч',
    'DD' : 'г',
    'PJ' : 'ю',
    'KK' : 'б',
    'NB' : 'ж',
    'HF' : 'Н',
    'PB' : 'М',
    'LA' : 'П',
    'EO' : 'В',
    'FP' : 'Т',
    'FC' : 'Ш',
    'HN' : 'Б',
    'MB' : 'С',
    'KO' : 'О',
    'KJ' : 'К',
    'DC' : '1',
    'OP' : '2',
    'GA' : '3',
    'KB' : '4',
    'PH' : '5',
    'GH' : '7',
    'AJ' : '0',
    'GN' : '.',
    'JE' : ',',
    'EG' : '—',
    'MH' : '–',
    'LM' : '(',
    'EC' : ')',
    'DL' : '-',
}

pair_exist = []

result = ''
for block in blocks:
    word = ''
    for i in range(len(sdvig)):
        pair = f'{block[sdvig[i][0]]}{block[sdvig[i][1]]}'
        if pair in alphabet:
            word += alphabet[pair]
            if pair not in pair_exist:
                pair_exist.append(pair)
        else:
            word += UNKNOWN_SYMBOL
    result += word
    
    e = word.find(UNKNOWN_SYMBOL)
    if e != -1:
       result += f'[{block[sdvig[e][0]]}{block[sdvig[e][1]]}]'

print(result)